-- ============================================================================
-- 018 — notifications
--
-- Per-user bell notifications ("nudges") generated by the system when
-- something happens that's worth an eyeball — e.g. a teacher hands in a
-- weekly plan, a main teacher submits the month's attendance, or a mark
-- column is opened. Announcements created by admins live in `notices`
-- (with read receipts); the bell merges the two streams for display.
--
-- Apply via Supabase dashboard → SQL Editor → New query → Run.
-- ============================================================================

CREATE TABLE IF NOT EXISTS notifications (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    school_id   UUID NOT NULL REFERENCES schools (id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,

    -- What kind of nudge this is: 'plan_submitted', 'plan_reviewed',
    -- 'attendance_submitted', 'mark_column', ... Free-form so new producers
    -- don't need a migration.
    kind        TEXT NOT NULL,

    title       TEXT NOT NULL,
    body        TEXT NOT NULL DEFAULT '',

    -- Optional in-app path the bell should open when the item is clicked,
    -- e.g. '/app/planning'.
    link        TEXT,

    -- Idempotency key chosen by the producer (e.g. 'assessment:<uuid>').
    -- Generating the same nudge twice must never create a second row —
    -- enforced by the UNIQUE (user_id, dedupe_key) below.
    dedupe_key  TEXT NOT NULL,

    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (user_id, dedupe_key)
);

-- Bell queries always read one user's newest items.
CREATE INDEX IF NOT EXISTS notifications_user_recent_idx
    ON notifications (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS notifications_school_idx
    ON notifications (school_id);
